[package]
name = "rust_tetris"
version = "0.1.0"
authors = ["Juho Sepänmaa <sepanmaa@cs.helsinki.fi>"]

[dependencies]
rand = "0.3"

[dependencies.sdl2]
version = "0.27"
default-features = false
features = ["ttf"]
